modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - adwaita-gtk2-theme
      - libadwaita
      - gammastep
    remove:
      - firefox
      - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - geoclue.service
    user:
      enabled:
        - kanshi.service
        - gammastep.service

  - type: gschema-overrides
    include:
      - zz1.gschema.override

  - type: signing
